<a href="https://colab.research.google.com/github/tghri499/DAP/blob/main/numpy_array_search.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x) 

(array([3, 5, 6], dtype=int64),)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x) 

(array([1, 3, 5, 7], dtype=int64),)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x) 

(array([0, 2, 4, 6], dtype=int64),)


In [ ]:
#The number 7 should be inserted on index 1 to remain the sort order.
#The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.

import numpy as np

arr = np.array([6, 7, 18, 19])

x = np.searchsorted(arr,11)

print(x) 

2


In [ ]:
import numpy as np

arr = np.array([6, 7, 18, 29])

x = np.searchsorted(arr, 19, side='right')

print(x) 

3


In [ ]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x) 

[1 2 3]
